apiVersion: batch/v1
kind: Job
metadata:
  name: PLACEHOLDER
  labels:
    kueue.x-k8s.io/queue-name: p5-queue
    kueue.x-k8s.io/max-exec-time-seconds: "10800"
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: alphafold-inference
          image: PLACEHOLDER
          command:
            - bash
            - -c
            - |
              set -exo pipefail

              # generate chemical data
              python -c "from alphafold3.build_data import build_data; build_data()"

              # generate model parameters
              python /usr/local/bin/generate_af_parameters.py \
                --input-parameters-file /opt/alphafold_input_data/model_parameters.md \
                --out-model-dir /opt/alphafold/model

              # inference
              python /usr/local/bin/af3_inference_benchmark.py \
                --input-json-path /opt/alphafold_input_data/input_sequences/bench_L00512.json \
                --model-dir /opt/alphafold/model \
                --output-json output.json
          resources:
            limits:
              nvidia.com/gpu: 1
      imagePullSecrets:
        - name: PLACEHOLDER
