declare const React: any;

// ---------------------------------------------------------------------------
// Type definitions
// ---------------------------------------------------------------------------

interface ColumnDef {
  id: string;
  label: string;
  width: number; // grid units
}

interface CellDef {
  width: number;
  label?: string;
  projects: string[];
}

interface RowDef {
  id: string;
  label: string;
  cells: CellDef[];
}

interface ProjectOverview {
  title: string;
  description: string;
  href?: string;
}

interface ProjectDef {
  id: string;
  name: string;
  category: string;
  href?: string;
  nvidia_participates?: boolean;
  isStatic?: boolean;
  overview?: ProjectOverview;
}

interface EcosystemData {
  columns: ColumnDef[];
  rows: RowDef[];
  projects: ProjectDef[];
}

// ---------------------------------------------------------------------------
// ECOSYSTEM-DATA:START — generated by scripts/build-ecosystem.mjs
const DATA: EcosystemData = {
  columns: [
    { id: "tooling", label: "Tooling", width: 2 },
    { id: "training", label: "Training / Post-Training", width: 7 },
    { id: "inference", label: "Inference", width: 3 },
  ],
  rows: [
    {
      id: "frameworks", label: "Frameworks",
      cells: [
        { width: 2, projects: ["nsight", "nsys-jax"] },
        { width: 6, projects: ["maxtext", "maxdiffusion", "axlearn"] },
        { width: 2, projects: ["tokamax"] },
        { width: 2, projects: ["alphafold3"] },
      ],
    },
    {
      id: "ecosystem", label: "JAX ecosystem",
      cells: [
        { width: 2, label: "Profiling", projects: ["xprof"] },
        { width: 3, label: "Training libraries", projects: ["grain", "optax", "orbax", "tunix", "qwix", "flax", "pallas-mosaicgpu"] },
        { width: 3, label: "Scale & precision", projects: ["jaxpp", "te"] },
        { width: 2, label: "Kernels", projects: ["warp", "cuequivariance", "cutile", "cutlass"] },
        { width: 2, label: "Inference", projects: ["flashinfer", "mlir-trt"] },
      ],
    },
    {
      id: "core", label: "JAX · XLA · Pathways",
      cells: [
        { width: 12, projects: ["jax", "xla", "pathways"] },
      ],
    },
    {
      id: "native-xla", label: "native XLA",
      cells: [
        { width: 2, projects: ["cupti"] },
        { width: 10, label: "native XLA", projects: ["cudnn", "cublas", "nccl", "nvshmem"] },
      ],
    },
    {
      id: "hardware", label: "Hardware",
      cells: [
        { width: 12, projects: ["hw-datacenter", "hw-workstation", "hw-rtx", "hw-jetson"] },
      ],
    },
  ],
  projects: [
    {
      id: "maxtext", name: "MaxText", category: "jax",
      href: "../frameworks/maxtext/README.md",
      nvidia_participates: true,
      overview: {
        title: "MaxText",
        description: "A scalable, high-performance JAX LLM framework (GPT, Llama, Gemma, Mistral, Mixtral). NVIDIA actively tests and contributes to MaxText and publishes a tuned container, making it the reference pre-training framework for JAX on NVIDIA GPUs.",
        href: "../frameworks/maxtext/README.md",
      },
    },
    {
      id: "maxdiffusion", name: "MaxDiffusion", category: "jax",
      href: "https://github.com/AI-Hypercomputer/maxdiffusion",
      nvidia_participates: true,
      overview: {
        title: "MaxDiffusion",
        description: "A scalable JAX framework for diffusion-model training, sharing MaxText's performance philosophy. Runs on NVIDIA GPUs through the same XLA/JAX stack.",
        href: "https://github.com/AI-Hypercomputer/maxdiffusion",
      },
    },
    {
      id: "axlearn", name: "AXLearn", category: "jax",
      href: "../frameworks/axlearn/README.md",
      nvidia_participates: true,
      overview: {
        title: "AXLearn",
        description: "Apple's deep-learning framework built on JAX and XLA for large-scale models such as the Fuji family. NVIDIA validates AXLearn on GPU clusters and publishes an axlearn container.",
        href: "../frameworks/axlearn/README.md",
      },
    },
    {
      id: "alphafold3", name: "AlphaFold3", category: "nvidia",
      href: "https://github.com/google-deepmind/alphafold3",
      overview: {
        title: "AlphaFold3",
        description: "DeepMind's protein-structure model. NVIDIA provides an optimized inference container (ghcr.io/nvidia/jax:alphafold) for running AlphaFold3 on GPUs.",
        href: "https://github.com/google-deepmind/alphafold3",
      },
    },
    {
      id: "nsight", name: "Nsight", category: "nvidia",
      href: "https://developer.nvidia.com/nsight-systems",
      overview: {
        title: "Nsight",
        description: "NVIDIA Nsight Systems (system-wide CPU+GPU+NVLink timeline) and Nsight Compute (per-kernel roofline, memory throughput, warp efficiency), bundled in the NGC JAX container for deep GPU-side profiling.",
        href: "https://developer.nvidia.com/nsight-systems",
      },
    },
    {
      id: "nsys-jax", name: "nsys-jax", category: "nvidia",
      href: "../nsys-jax.md",
      overview: {
        title: "nsys-jax",
        description: "A JAX-Toolbox wrapper around Nsight Systems that captures and post-processes profiles of JAX programs, aligning XLA/HLO with GPU timelines.",
        href: "../nsys-jax.md",
      },
    },
    {
      id: "xprof", name: "XProf", category: "jax",
      href: "https://github.com/openxla/xprof",
      overview: {
        title: "XProf",
        description: "OpenXLA's profiler — trace viewer, HLO op profile, memory viewer, and roofline analysis. On NVIDIA GPUs it collects traces via CUPTI and shares the XLA HLO graph view; NVIDIA contributes to the GPU path.",
        href: "https://github.com/openxla/xprof",
      },
    },
    {
      id: "grain", name: "Grain", category: "jax",
      href: "https://github.com/google/grain",
      overview: {
        title: "Grain",
        description: "A deterministic, checkpointable input-data pipeline for JAX. Framework-independent and runs on NVIDIA GPUs.",
        href: "https://github.com/google/grain",
      },
    },
    {
      id: "optax", name: "Optax", category: "jax",
      href: "https://github.com/google-deepmind/optax",
      nvidia_participates: true,
      overview: {
        title: "Optax",
        description: "A library of composable gradient-processing and optimization transforms for JAX, used by training frameworks across the ecosystem.",
        href: "https://github.com/google-deepmind/optax",
      },
    },
    {
      id: "orbax", name: "Orbax", category: "jax",
      href: "https://github.com/google/orbax",
      nvidia_participates: true,
      overview: {
        title: "Orbax",
        description: "Any-scale distributed checkpointing for JAX, shared across TPU and GPU workflows.",
        href: "https://github.com/google/orbax",
      },
    },
    {
      id: "tunix", name: "Tunix", category: "jax",
      href: "https://github.com/google/tunix",
      overview: {
        title: "Tunix",
        description: "A JAX-native framework for post-training and alignment — supervised fine-tuning and RL methods such as PPO and DPO/RLHF. Framework-independent and runs on NVIDIA GPUs.",
        href: "https://github.com/google/tunix",
      },
    },
    {
      id: "qwix", name: "Qwix", category: "jax",
      href: "https://github.com/google/qwix",
      overview: {
        title: "Qwix",
        description: "A JAX-native quantization library (PTQ, QAT, and QLoRA). Its non-intrusive interception applies quantization without changing model code, targeting XLA on both NVIDIA GPUs and TPUs.",
        href: "https://github.com/google/qwix",
      },
    },
    {
      id: "flax", name: "Flax", category: "jax",
      href: "https://github.com/google/flax",
      nvidia_participates: true,
      overview: {
        title: "Flax",
        description: "A flexible neural-network authoring library for JAX (the NNX API). Used across NVIDIA's NGC containers and Google's MaxText; NVIDIA contributes upstream.",
        href: "https://github.com/google/flax",
      },
    },
    {
      id: "pallas-mosaicgpu", name: "Pallas / Mosaic GPU", category: "jax",
      href: "https://docs.jax.dev/en/latest/pallas/index.html",
      overview: {
        title: "Pallas / Mosaic GPU",
        description: "Pallas is JAX's kernel-authoring API; on NVIDIA GPUs it lowers primarily to the Mosaic GPU backend (Hopper+), exposing the GMEM to SMEM to registers pipeline, TMA async copies, and warp specialization. A Triton backend remains as an Ampere+ fallback.",
        href: "https://docs.jax.dev/en/latest/pallas/index.html",
      },
    },
    {
      id: "jaxpp", name: "JaxPP", category: "nvidia",
      href: "https://github.com/NVIDIA/JaxPP",
      overview: {
        title: "JaxPP",
        description: "NVIDIA's pipeline-parallelism library for JAX, splitting large-model training into pipeline stages across GPUs and nodes with flexible scheduling to keep devices busy.",
        href: "https://github.com/NVIDIA/JaxPP",
      },
    },
    {
      id: "te", name: "TransformerEngine", category: "nvidia",
      href: "https://github.com/NVIDIA/TransformerEngine",
      overview: {
        title: "TransformerEngine",
        description: "NVIDIA's mixed-precision training library. The JAX extension delivers FP8, MXFP8, and NVFP4 training on Hopper and Blackwell Tensor Cores and ships inside NVIDIA's NGC JAX container, unlocking low-precision paths that reach deeper into NVIDIA silicon than framework-agnostic quantization.",
        href: "https://github.com/NVIDIA/TransformerEngine",
      },
    },
    {
      id: "warp", name: "Warp", category: "nvidia",
      href: "https://github.com/NVIDIA/warp",
      overview: {
        title: "Warp",
        description: "NVIDIA Warp is a Python framework for writing high-performance, differentiable GPU kernels (simulation, geometry, custom ops). Warp kernels can be called from JAX through the foreign-function interface.",
        href: "https://github.com/NVIDIA/warp",
      },
    },
    {
      id: "cuequivariance", name: "cuEquivariance", category: "nvidia",
      href: "https://github.com/NVIDIA/cuEquivariance",
      overview: {
        title: "cuEquivariance",
        description: "An NVIDIA library that accelerates equivariant neural networks — common in chemistry, materials, and structural biology — with optimized primitives and JAX bindings for GPU execution.",
        href: "https://github.com/NVIDIA/cuEquivariance",
      },
    },
    {
      id: "cutile", name: "cuTile", category: "nvidia",
      overview: {
        title: "cuTile",
        description: "NVIDIA's tile-based programming model for authoring GPU kernels at a higher level than raw CUDA: computation is expressed over tiles that the compiler maps onto the hardware.",
      },
    },
    {
      id: "cutlass", name: "CUTLASS", category: "nvidia",
      href: "https://github.com/NVIDIA/cutlass",
      overview: {
        title: "CUTLASS",
        description: "NVIDIA's open-source CUDA templates for high-performance GEMM and convolution — a building block for custom kernels and library backends on NVIDIA GPUs.",
        href: "https://github.com/NVIDIA/cutlass",
      },
    },
    {
      id: "tokamax", name: "Tokamax", category: "jax",
      href: "https://github.com/google/tokamax",
      nvidia_participates: true,
      overview: {
        title: "Tokamax",
        description: "A curated library of state-of-the-art custom kernels (attention and more) exposed through Pallas, with per-hardware autotuned implementations on NVIDIA GPUs.",
        href: "https://github.com/google/tokamax",
      },
    },
    {
      id: "flashinfer", name: "FlashInfer", category: "nvidia",
      href: "https://github.com/flashinfer-ai/flashinfer",
      overview: {
        title: "FlashInfer",
        description: "A high-performance library of attention and LLM-serving kernels for NVIDIA GPUs (prefill/decode attention, paged KV cache), used to accelerate JAX/GPU inference paths.",
        href: "https://github.com/flashinfer-ai/flashinfer",
      },
    },
    {
      id: "mlir-trt", name: "MLIR-TRT", category: "nvidia",
      href: "https://github.com/NVIDIA/TensorRT-Incubator",
      overview: {
        title: "MLIR-TRT",
        description: "MLIR-TensorRT — an MLIR-based compiler path that lowers StableHLO to optimized TensorRT engines for NVIDIA inference.",
        href: "https://github.com/NVIDIA/TensorRT-Incubator",
      },
    },
    {
      id: "jax", name: "JAX", category: "jax",
      href: "https://github.com/jax-ml/jax",
      nvidia_participates: true,
      overview: {
        title: "JAX",
        description: "Accelerator-oriented array computation with composable transforms — jit, grad, vmap, pmap. Hardware-agnostic and the foundation of the whole stack; runs on NVIDIA GPUs through XLA's CUDA backend.",
        href: "https://github.com/jax-ml/jax",
      },
    },
    {
      id: "xla", name: "XLA", category: "jax",
      href: "https://github.com/openxla/xla",
      nvidia_participates: true,
      overview: {
        title: "XLA",
        description: "The shared JIT compiler behind JAX. Programs trace to StableHLO, which XLA:GPU lowers via LLVM NVPTX to PTX/SASS, calling cuBLAS and cuDNN as library ops. OpenXLA is co-developed by NVIDIA alongside Google and others.",
        href: "https://github.com/openxla/xla",
      },
    },
    {
      id: "pathways", name: "Pathways", category: "other",
      overview: {
        title: "Pathways",
        description: "Google's proprietary single-controller runtime for orchestrating large TPU pods. Shown for context — it is not part of the NVIDIA GPU path, where multi-node JAX uses HPC-X/OpenMPI, Ray, or SLURM.",
      },
    },
    {
      id: "cupti", name: "CUPTI", category: "nvidia",
      href: "https://docs.nvidia.com/cupti/",
      overview: {
        title: "CUPTI",
        description: "The CUDA Profiling Tools Interface — the low-level API that profilers (including XProf's GPU path and nsys-jax) use to collect GPU traces and metrics.",
        href: "https://docs.nvidia.com/cupti/",
      },
    },
    {
      id: "cudnn", name: "cuDNN", category: "nvidia",
      href: "https://developer.nvidia.com/cudnn",
      overview: {
        title: "cuDNN",
        description: "NVIDIA's deep-learning primitive library, called by XLA:GPU for convolutions and attention. Provides fused FlashAttention and paged-attention kernels used under JAX.",
        href: "https://developer.nvidia.com/cudnn",
      },
    },
    {
      id: "cublas", name: "cuBLAS / cuBLASLt", category: "nvidia",
      href: "https://developer.nvidia.com/cublas",
      overview: {
        title: "cuBLAS / cuBLASLt",
        description: "NVIDIA's GEMM library (cuBLAS / cuBLASLt), invoked by XLA:GPU for matrix multiply — including FP8 and MXFP8 matmul on Hopper and Blackwell.",
        href: "https://developer.nvidia.com/cublas",
      },
    },
    {
      id: "nccl", name: "NCCL", category: "nvidia",
      href: "https://developer.nvidia.com/nccl",
      overview: {
        title: "NCCL",
        description: "The NVIDIA Collective Communications Library — topology-aware AllReduce, AllGather, and ReduceScatter across NVLink and InfiniBand. JAX/XLA drives multi-GPU and multi-node collectives through NCCL.",
        href: "https://developer.nvidia.com/nccl",
      },
    },
    {
      id: "nvshmem", name: "NVSHMEM", category: "nvidia",
      href: "https://developer.nvidia.com/nvshmem",
      overview: {
        title: "NVSHMEM",
        description: "GPU-initiated symmetric memory for low-latency, fine-grained communication. Integrates with Mosaic GPU kernels to hide latency, complementing NCCL's bulk collectives.",
        href: "https://developer.nvidia.com/nvshmem",
      },
    },
    {
      id: "hw-datacenter", name: "Datacenter", category: "nvidia",
      isStatic: true,
    },
    {
      id: "hw-workstation", name: "Workstations", category: "nvidia",
      isStatic: true,
    },
    {
      id: "hw-rtx", name: "RTX series", category: "nvidia",
      isStatic: true,
    },
    {
      id: "hw-jetson", name: "Jetson", category: "nvidia",
      isStatic: true,
    },
  ],
};
// ECOSYSTEM-DATA:END

// ---------------------------------------------------------------------------
// Category styling — rgba tints so the diagram reads on both light and dark
// page backgrounds (same intent as the original color-mix() CSS approach)
// ---------------------------------------------------------------------------

const NV_GREEN = "#76B900";
const JAX_BLUE = "#5e9bf0";
const OTHER_GRAY = "#6b7280";

// background tint + inset ring color per category
const CAT_STYLE: Record<string, { bg: string; ring: string }> = {
  nvidia: { bg: "rgba(118,185,0,0.12)",   ring: NV_GREEN   },
  jax:    { bg: "rgba(94,155,240,0.12)",  ring: JAX_BLUE   },
  other:  { bg: "rgba(107,114,128,0.14)", ring: OTHER_GRAY },
};
const CAT_DEFAULT = { bg: "rgba(107,114,128,0.10)", ring: OTHER_GRAY };

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function totalUnits(columns: ColumnDef[]): number {
  return columns.reduce((s, c) => s + c.width, 0);
}

function catStyle(project: ProjectDef): { bg: string; ring: string } {
  const base = CAT_STYLE[project.category] ?? CAT_DEFAULT;
  // nvidia_participates overrides the ring to green regardless of category
  if (project.nvidia_participates && project.category !== "nvidia") {
    return { bg: base.bg, ring: NV_GREEN };
  }
  return base;
}

// ---------------------------------------------------------------------------
// Legend
// ---------------------------------------------------------------------------

function Legend() {
  const items = [
    { bg: "rgba(118,185,0,0.12)",   ring: NV_GREEN,   label: "NVIDIA-developed / optimized" },
    { bg: "rgba(94,155,240,0.12)",  ring: JAX_BLUE,   label: "JAX-native / OSS ecosystem" },
    { bg: "rgba(107,114,128,0.14)", ring: OTHER_GRAY,  label: "Other / runtime" },
    { bg: "rgba(94,155,240,0.12)",  ring: NV_GREEN,   label: "NVIDIA participates" },
  ];
  return (
    <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", margin: "0 0 10px", fontSize: "0.68rem" }}>
      {items.map((item) => (
        <span key={item.label} style={{ display: "inline-flex", alignItems: "center", gap: "6px" }}>
          <span
            style={{
              display: "inline-block",
              width: "14px",
              height: "11px",
              borderRadius: "1px",
              background: item.bg,
              boxShadow: `inset 0 0 0 1.5px ${item.ring}`,
            }}
          />
          {item.label}
        </span>
      ))}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Column headers
// ---------------------------------------------------------------------------

function ColumnHeaders({ columns }: { columns: ColumnDef[] }) {
  return (
    <>
      {columns.map((col) => (
        <div
          key={col.id}
          style={{
            gridColumn: `span ${col.width}`,
            textAlign: "center",
            fontWeight: 700,
            fontSize: "0.64rem",
            padding: "3px 6px",
            borderRadius: "2px",
            background: "rgba(118,185,0,0.10)",
            border: "1px solid rgba(118,185,0,0.45)",
          }}
        >
          {col.label}
        </div>
      ))}
    </>
  );
}

// ---------------------------------------------------------------------------
// Project node (chip)
// ---------------------------------------------------------------------------

function ProjectNode({
  project,
  selected,
  onClick,
}: {
  project: ProjectDef;
  selected: boolean;
  onClick: () => void;
}) {
  const { bg, ring } = catStyle(project);
  const isClickable = !project.isStatic;

  return (
    <button
      onClick={isClickable ? onClick : undefined}
      style={{
        display: "inline-block",
        background: bg,
        boxShadow: selected
          ? `0 0 0 2px ${NV_GREEN}, inset 0 0 0 2px ${ring}`
          : `inset 0 0 0 2px ${ring}`,
        outline: "none",
        border: "none",
        borderRadius: "2px",
        fontWeight: selected ? 700 : 600,
        fontSize: "0.82rem",
        lineHeight: 1.2,
        padding: "4px 9px",
        color: "inherit",
        cursor: isClickable ? "pointer" : "default",
        textDecoration: "none",
        whiteSpace: "nowrap",
      }}
      aria-pressed={selected || undefined}
    >
      {project.name}
    </button>
  );
}

// ---------------------------------------------------------------------------
// Grid cell
// ---------------------------------------------------------------------------

function Cell({
  cell,
  projectMap,
  selectedId,
  onSelect,
}: {
  cell: CellDef;
  projectMap: Map<string, ProjectDef>;
  selectedId: string | null;
  onSelect: (id: string) => void;
}) {
  const hasLabel = !!cell.label;
  return (
    <div
      style={{
        gridColumn: `span ${cell.width}`,
        position: "relative",
        display: "flex",
        flexWrap: "wrap",
        gap: "7px 5px",
        justifyContent: "center",
        alignContent: "center",
        alignItems: "center",
        padding: hasLabel ? "1.5rem 5px 8px" : "7px 5px 8px",
        border: "1px dashed rgba(128,128,128,0.32)",
        borderRadius: "2px",
        minHeight: "1.8rem",
      }}
    >
      {hasLabel && (
        <span
          style={{
            position: "absolute",
            top: "3px",
            left: "5px",
            fontSize: "0.5rem",
            fontWeight: 700,
            letterSpacing: "0.04em",
            textTransform: "uppercase",
            opacity: 0.55,
            pointerEvents: "none",
          }}
        >
          {cell.label}
        </span>
      )}
      {cell.projects.map((pid) => {
        const proj = projectMap.get(pid);
        if (!proj) return null;
        return (
          <ProjectNode
            key={pid}
            project={proj}
            selected={selectedId === pid}
            onClick={() => onSelect(pid)}
          />
        );
      })}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Overview panel
// ---------------------------------------------------------------------------

function OverviewPanel({
  project,
  onClose,
}: {
  project: ProjectDef;
  onClose: () => void;
}) {
  const ov = project.overview;
  const { ring } = catStyle(project);
  return (
    <div
      style={{
        marginTop: "0.5rem",
        border: `1px solid rgba(118,185,0,0.4)`,
        borderTop: `3px solid ${NV_GREEN}`,
        borderRadius: "5px",
        background: "rgba(118,185,0,0.06)",
        padding: "0.9rem 1.1rem",
        fontSize: "0.85rem",
        position: "relative",
      }}
    >
      <button
        onClick={onClose}
        style={{
          position: "absolute",
          top: "8px",
          right: "10px",
          background: "transparent",
          border: "none",
          opacity: 0.5,
          fontSize: "16px",
          cursor: "pointer",
          lineHeight: 1,
          padding: "0 4px",
          color: "inherit",
        }}
        aria-label="Close"
      >
        ×
      </button>
      <strong style={{ display: "block", marginBottom: "0.4rem" }}>
        <span
          style={{
            display: "inline-block",
            background: "rgba(0,0,0,0.08)",
            boxShadow: `inset 0 0 0 2px ${ring}`,
            borderRadius: "2px",
            padding: "2px 7px",
            marginRight: "8px",
            fontSize: "0.82rem",
          }}
        >
          {ov?.title ?? project.name}
        </span>
        {project.nvidia_participates && (
          <span style={{ fontSize: "0.75rem", color: NV_GREEN }}>
            NVIDIA participates
          </span>
        )}
      </strong>
      {ov?.description && (
        <p style={{ margin: "0 0 0.5rem", lineHeight: 1.55 }}>{ov.description}</p>
      )}
      {(ov?.href ?? project.href) && (
        <a
          href={ov?.href ?? project.href}
          target="_blank"
          rel="noopener noreferrer"
          style={{ color: NV_GREEN, fontWeight: 600, textDecoration: "none", fontSize: "0.82rem" }}
        >
          Learn more →
        </a>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export function EcosystemDiagram() {
  const [selectedId, setSelectedId] = React.useState(null);

  const projectMap = React.useMemo(
    () => new Map(DATA.projects.map((p: ProjectDef) => [p.id, p])),
    []
  );

  function handleSelect(id: string) {
    setSelectedId((prev: string | null) => (prev === id ? null : id));
  }

  const selectedProject = selectedId ? projectMap.get(selectedId) : null;
  const units = totalUnits(DATA.columns);

  return (
    <div style={{ margin: "1.25rem 0" }}>
      <Legend />
      <div
        role="group"
        aria-label="JAX on NVIDIA GPU stack"
        style={{
          display: "grid",
          gridTemplateColumns: `repeat(${units}, 1fr)`,
          gap: "4px",
          fontSize: "0.78rem",
          overflowX: "auto",
          minWidth: "560px",
        }}
      >
        <ColumnHeaders columns={DATA.columns} />
        {DATA.rows.map((row: RowDef) =>
          row.cells.map((cell, ci) => (
            <Cell
              key={`${row.id}-${ci}`}
              cell={cell}
              projectMap={projectMap}
              selectedId={selectedId}
              onSelect={handleSelect}
            />
          ))
        )}
      </div>
      {selectedProject ? (
        <OverviewPanel
          project={selectedProject}
          onClose={() => setSelectedId(null)}
        />
      ) : (
        <div
          style={{
            marginTop: "0.5rem",
            border: "1px solid rgba(118,185,0,0.4)",
            borderTop: `3px solid ${NV_GREEN}`,
            borderRadius: "5px",
            background: "rgba(118,185,0,0.06)",
            padding: "0.9rem 1.1rem",
            fontSize: "0.85rem",
            fontStyle: "italic",
            opacity: 0.55,
          }}
        >
          Select a project to see what it is and where it fits.
        </div>
      )}
    </div>
  );
}
