name: Launch workload on GKE with XPK

description: "Launch a JobSet workload on GKE with XPK. Upload artifacts from container to GCS and GitHub Actions."

inputs:
  GCP_PROJECT:
    description: 'GCP project ID'
    default: nv-jaxtoolboxgcp-20240925
    type: string
  GKE_CLUSTER:
    description: 'GKE cluster name'
    default: jtb-2026-05-06
    required: false
    type: string
  GCP_REGION:
    description: 'GCP region of the cluster'
    default: europe-west4
    required: false
    type: string
  CLUSTER_DEVICE:
    description: 'GPU device type in the cluster'
    default: h100-mega-80gb-8
    required: false
    type: string
  GPU_ARCH:
    description: 'GPU architecture name'
    default: H100
    required: false
    type: string
  NUM_NODES:
    description: 'Number of nodes to use in JobSet (n.b each a3-megagpu-8g node has 8xGPU)'
    default: 2
    required: false
    type: string
  MAIN_CONTAINER_NAME:
    description: 'Name of the main contianer in an XPK JobSet (fixed in xpk)'
    default: gpu-image
    required: false
    type: string
  CONTAINER_OUTPUT_PATH:
    description: 'Output directory for artifacts'
    default: /opt/output
    required: false
    type: string
  GCS_BUCKET:
    description: 'GCS bucket to which CI output artifacts will be uploaded'
    default: jaxtoolbox-ci
    required: false
    type: string
  IMAGE:
    description: 'URI of image to use in JobSet'
    required: false
    default: ghcr.io/nvidia/jax:latest
    type: string
  COMMAND:
    description: 'Command to run in main container on JobSet start up'
    required: false
    default: 'nvidia-smi; free -h;'
    type: string
  ENVS:
    description: 'Environment variables to pass to xpk for setting in JobSet (delimited by ;)'
    required: false
    default: ''
    type: string
  EXIT_COMMAND:
    description: 'Command to set exit code'
    required: false
    default: 'exit \$EXIT_CODE'
    type: string
  NAME:
    description: 'Workload name prefix for XPK, also used to name uploaded artifact'
    required: false
    default: 'xpk'
    type: string
  XPK_VERSION:
    description: 'XPK release tag'
    required: false
    default: 'v1.0.0'
    type: string
  XPK_PYTHON:
    description: 'Python version for XPK'
    required: false
    default: '3.12.10'
    type: string
  GITHUB_TOKEN:
    description: 'GitHub artifact registry login token'
    type: string
    required: true
  NVCR_TOKEN:
    description: 'NVCR artifact registry login token'
    type: string
    required: true
  STATISTICS_SCRIPT:
    description: 'Commands to extract NUM_ERRORS NUM_TESTS NUM_PASSED NUM_FAILED values from logs'
    type: string
    required: false
    default: |
      NUM_ERRORS=0;
      if [ \${JOBSET_EXIT_CODE} -ne 0 ]; then
        NUM_FAILED=1;
        NUM_PASSED=0;
      else
        NUM_FAILED=0;
        NUM_PASSED=1;
      fi;
      NUM_TESTS=\$((NUM_FAILED + NUM_PASSED));

runs:
  using: 'composite'
  steps:

  - name: Check cluster online
    id: check
    shell: bash -x -u {0}
    run: |
      gcloud container clusters list | grep ${{ inputs.GKE_CLUSTER }} | grep RUNNING > /dev/null 

      if [[ "$?" == "1" ]]; then
        echo "Cluster ${{ inputs.GKE_CLUSTER }} does not exist"
        echo "online=false" >> ${GITHUB_OUTPUT}
        exit 0
      fi

      # get gpu nodepool name
      GPU_NODEPOOL=$(gcloud container clusters describe ${{ inputs.GKE_CLUSTER }} --zone ${{ inputs.GCP_REGION }} | yq -r '.nodePools[1].name' | grep -v system)

      # inspect gpu nodes
      GPU_NODES_ONLINE=$(kubectl get nodes -l cloud.google.com/gke-nodepool=${GPU_NODEPOOL} -o json | jq '.items | length >= '${{ inputs.NUM_NODES }})
      echo "online=${GPU_NODES_ONLINE}" >> ${GITHUB_OUTPUT}

  - name: Set workload name
    if: steps.check.outputs.online == 'true'
    shell: bash -x -e -u {0}
    run: |
      JOBSET_NAME="${{ inputs.NAME }}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
      DATE=$(date +'%Y-%m-%d')
      GCS_ARTIFACT_PATH="gs://${{ inputs.GCS_BUCKET }}/${{ inputs.NAME }}/${DATE}/${JOBSET_NAME}"

      echo "JOBSET_NAME=${JOBSET_NAME}" >> ${GITHUB_ENV}
      echo "DATE=${DATE}" >> ${GITHUB_ENV}
      echo "GCS_ARTIFACT_PATH=${GCS_ARTIFACT_PATH}" >> ${GITHUB_ENV}

  - name: Login to GitHub Container Registry
    if: steps.check.outputs.online == 'true'
    uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.repository_owner }}
      password: ${{ inputs.GITHUB_TOKEN }}

  - name: Login to nvcr.io Container Registry
    if: steps.check.outputs.online == 'true'
    uses: docker/login-action@v3
    with:
      registry: nvcr.io
      username: $oauthtoken
      password: ${{ inputs.NVCR_TOKEN }}

  - name: k8s store and delete image secret
    if: steps.check.outputs.online == 'true'
    id: store-token
    uses: ./.github/actions/store-delete-k8s-ghcr

  - name: Setup environment
    if: steps.check.outputs.online == 'true'
    shell: bash -x -e -u {0}
    run: |
      mkdir -p ${JOBSET_NAME}
      uv venv --verbose --python=${{ inputs.XPK_PYTHON }} --directory=${JOBSET_NAME}
      source ${JOBSET_NAME}/.venv/bin/activate
     
      git clone --depth=1 --branch=${{ inputs.XPK_VERSION }} https://github.com/AI-Hypercomputer/xpk.git ${JOBSET_NAME}/xpk
     
      # apply XPK workload patch
      PATCH_PATH=.github/gke-workflow/xpk/${{ inputs.XPK_VERSION}}
      ls ${PATCH_PATH}/*.patch | xargs -I {} git apply --unsafe-paths {} --directory ${JOBSET_NAME}/xpk

      # install xpk
      sed 's@pip install -e \.@'$(which uv)' pip install \.@g' -i ${JOBSET_NAME}/xpk/Makefile
      cd ${JOBSET_NAME}/xpk && sudo make pip-install; cd -

  - name: Show environment
    if: steps.check.outputs.online == 'true'
    shell: bash -x -e -u {0}
    run: |
      gcloud version

      source ${JOBSET_NAME}/.venv/bin/activate
      python --version
      xpk version

  - name: Set workload commands
    if: steps.check.outputs.online == 'true'
    shell: bash -x -e -u {0}
    run: |
      # install dependencies to enable export artifacts from container to gcs bucket
      PRELUDE="
          apt install -y ripgrep > /dev/null;
          curl -LO https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz;
          tar xf google-cloud-cli-linux-x86_64.tar.gz;
          ./google-cloud-sdk/install.sh --quiet > /dev/null;
          ./google-cloud-sdk/bin/gcloud init;

          mkdir -p /usr/share/workload;
          mkdir -p ${{ inputs.CONTAINER_OUTPUT_PATH }};"

      PRELUDE+="
          if [ -n \"\${NCCL_LIB_DIR:-}\" ]; then
              if [ -f \"\${NCCL_LIB_DIR}/nccl-env-profile.sh\" ]; then
                  NCCL_LIB_DIR=\${NCCL_LIB_DIR} . \${NCCL_LIB_DIR}/nccl-env-profile.sh;
              fi;
              export LD_LIBRARY_PATH=\${NCCL_LIB_DIR}:\${LD_LIBRARY_PATH};
              if [ -z \"\${NCCL_TUNER_CONFIG_PATH:-}\" ]; then
                  export NCCL_TUNER_CONFIG_PATH=\${NCCL_LIB_DIR}/a3plus_tuner_config.textproto;
              fi;
              if [ -z \"\${NCCL_SHIMNET_GUEST_CONFIG_CHECKER_CONFIG_FILE:-}\" ]; then
                  export NCCL_SHIMNET_GUEST_CONFIG_CHECKER_CONFIG_FILE=\${NCCL_LIB_DIR}/a3plus_guest_config.textproto;
              fi;
          fi;
      "

      # gsutil command to export logs from container's /opt/output to bucket
      POSTLUDE="
          ./google-cloud-sdk/bin/gsutil cp -r ${{ inputs.CONTAINER_OUTPUT_PATH }}/ ${GCS_ARTIFACT_PATH}/node-0\$NODE_RANK;
          ${{ inputs.EXIT_COMMAND }}
      "

      CMD="${{ inputs.COMMAND }}"

      # set container commands in-line
      PRELUDE=$(echo ${PRELUDE} | sed 's/\n/\ /g')
      POSTLUDE=$(echo ${POSTLUDE} | sed 's/\n/\ /g')
      CMD=$(echo ${CMD} | sed 's/\n/\ /g')

      echo "CMD=${PRELUDE} ${CMD} ${POSTLUDE}" >> ${GITHUB_ENV}

  - name: Create workload on cluster with XPK
    if: steps.check.outputs.online == 'true'
    shell: bash -x -e -u {0}
    run: |
      source ${JOBSET_NAME}/.venv/bin/activate
      cd ${JOBSET_NAME}/xpk

      args=(
          --project=${{ inputs.GCP_PROJECT }}
          --cluster=${{ inputs.GKE_CLUSTER }}
          --zone=${{ inputs.GCP_REGION }}
          --workload=${JOBSET_NAME}
          --docker-image=${{ inputs.IMAGE }}
          --device-type=${{ inputs.CLUSTER_DEVICE }}
          --num-nodes=${{ inputs.NUM_NODES }}
          --num-slices=${{ inputs.NUM_NODES }}
          --priority=high
          --scheduler=gke.io/topology-aware-auto
      )

      version_geq() {
        if [[ $1 == $2 ]]; then
          return 0
        elif [[ $(echo -e "$1\n$2" | sort -V | head -n 1) != "$1" ]]; then
          return 0
        fi
        return 1
      }

      if version_geq "${{ inputs.XPK_VERSION }}" "v0.10.0"; then
          args+=(
              --docker-image-pull-secret=${{ steps.store-token.outputs.token-name }}
              --env="JAX_COORDINATOR_PORT=3389"
              --env="JAX_COORDINATOR_ADDRESS=\$(JOBSET_NAME)-\$(REPLICATED_JOB_NAME)-0-0.\$(JOBSET_NAME):3389"
              --env="NHOSTS=${{ inputs.NUM_NODES }}"
          )

        envs_flat=$(echo "${{ inputs.ENVS }}" | tr '\n' ' ')
        IFS=';' read -ra env_vars <<< "${envs_flat}"
        for env in "${env_vars[@]}"; do
            env=$(echo "${env}" | xargs)
            [[ -n "${env}" ]] && args+=("--env=${env}")
        done
      fi

      if version_geq "${{ inputs.XPK_VERSION }}" "v1.0.0"; then
        XPK_COMMAND=xpk
      else
        XPK_COMMAND="python xpk.py"
      fi
      ${XPK_COMMAND} workload create "${args[@]}" --command="${CMD}"

  - name: Show JobSet manifest
    if: steps.check.outputs.online == 'true'
    shell: bash -ux {0}
    run: |
      kubectl get jobset/${JOBSET_NAME} -o yaml

  - name: Wait for JobSet to unsuspend on cluster
    if: steps.check.outputs.online == 'true'
    shell: bash -u {0}
    env:
      POLL_TIMEOUT: 10800
    run: |
      set -euo pipefail
  
      START=$(date +%s)
      JOBSET_ACTIVE=""
  
      while [[ "${JOBSET_ACTIVE:-}" != "true" ]]; do
        JOBSET_ACTIVE="$(
          kubectl get jobset -o json | jq -r '
            .items[]
            | select(.metadata.name == "'"${JOBSET_NAME}"'")
            | .status.replicatedJobsStatus[0].active == 1
          '
        )"
  
        NOW=$(date +%s)
        ELAPSED=$(( NOW - START ))
        if (( ELAPSED > POLL_TIMEOUT )); then
          echo "Timeout after waiting for JobSet ${JOBSET_NAME} to become active in the cluster"
          exit 1
        fi
  
        echo "Waiting for JobSet ${JOBSET_NAME} to become active in the cluster"
        sleep 10
      done
  
      echo "JobSet ${JOBSET_NAME} has just become active in the cluster"

  - name: Set JobSet Pods
    shell: bash -u {0}
    run: |
      echo "JOBSET_PODS=($(kubectl get pods -o json | jq -r '.items[].metadata | select(.labels."jobset.sigs.k8s.io/jobset-name" == "'${JOBSET_NAME}'") | .name' | tr '\n' ' '))" >> ${GITHUB_ENV}

  - name: Wait for JobSet readiness
    if: steps.check.outputs.online == 'true'
    shell: bash
    run: |
      set -euo pipefail

      for jobset_pod in ${JOBSET_PODS//[()]/}; do
        [[ -z "$jobset_pod" ]] && continue
        echo "Waiting for pod $jobset_pod in JobSet $JOBSET_NAME to become ready"
        kubectl wait --for=condition=Ready "pod/$jobset_pod" --timeout=30m
      done

  - name: Stream logs from JobSet Pods
    if: steps.check.outputs.online == 'true'
    shell: bash -u {0}
    run: |
      mkdir -p ${JOBSET_NAME}

      for jobset_pod in ${JOBSET_PODS//[()]/}; do
          kubectl logs --pod-running-timeout=1m -f --prefix=true --timestamps=true -c gpu-image ${jobset_pod} 2>&1 | tee -a ${JOBSET_NAME}/${jobset_pod}.log &
      done
      wait < <(jobs -p)

  - name: Set exit code from JobSet pods logs
    if: steps.check.outputs.online == 'true'
    shell: bash -u {0}
    run: |
      parse_pod_exit_code() {
        local pod=$1
        MAYBE_JOBSET_EXIT_CODE="$(cat ${JOBSET_NAME}/${pod}.log | grep -oE 'EXIT\_CODE=[0-9]+$')"
        echo ${MAYBE_JOBSET_EXIT_CODE} | grep -E 'EXIT\_CODE=[0-9]+$' > /dev/null

        if [ $? -ne 0 ]; then
          echo "The JobSet ${JOBSET_NAME} did not complete as expected " >&2
          echo "JOBSET_EXIT_CODE=1" >> ${GITHUB_ENV}
          exit 1
        fi

        echo "Pod ${pod} exited with ${MAYBE_JOBSET_EXIT_CODE}" >&2

        eval "export ${MAYBE_JOBSET_EXIT_CODE}"
        echo ${EXIT_CODE}
      }

      ALL_EXIT_CODES=0
      for jobset_pod in ${JOBSET_PODS//[()]/}; do
        POD_EXIT_CODE=$(parse_pod_exit_code ${jobset_pod})
        ALL_EXIT_CODES=$(( ALL_EXIT_CODES + POD_EXIT_CODE ))
      done

      echo "JOBSET_EXIT_CODE=${ALL_EXIT_CODES}" >> ${GITHUB_ENV}
      if [ ${ALL_EXIT_CODES} -gt 0 ]; then
        exit 1
      fi
      exit 0

  - name: Clean up JobSet from cluster
    if: steps.check.outputs.online == 'true'
    shell: bash -x -u {0}
    run: |
      kubectl delete jobset --wait ${JOBSET_NAME} || echo "JobSet ${JOBSET_NAME} does not exist"

  - name: Download artifacts from GCS to runner
    if: steps.check.outputs.online == 'true'
    shell: bash -x -u {0}
    run: |
      mkdir -p ${JOBSET_NAME}/output
      gsutil cp -r ${GCS_ARTIFACT_PATH} ${JOBSET_NAME}/output
      cp ${JOBSET_NAME}/*.log ${JOBSET_NAME}/output

  - name: Upload artifacts to GitHub Actions from runner
    if: steps.check.outputs.online == 'true'
    uses: actions/upload-artifact@v6
    with:
      name: ${{ inputs.NAME }}
      path: ${{ env.JOBSET_NAME }}/output/*

  - name: Emit unit test statistics
    if: ${{ !cancelled() }}
    shell: bash -xe -u {0}
    run: |
      STATISTICS_SCRIPT="${{ inputs.STATISTICS_SCRIPT }}"
      STATISTICS_SCRIPT=$(echo ${STATISTICS_SCRIPT} | sed 's/\n/\ /g')
      eval "${STATISTICS_SCRIPT}"

      if [[ ${NUM_ERRORS} > 0 ]] || [[ ${NUM_TESTS} == 0 ]]; then
        BADGE_COLOR=red
        BADGE_MESSAGE=error
        SUMMARY="${{ inputs.NAME }} unit test on ${{ inputs.GPU_ARCH }} did not complete due to errors."
        continue
      else
        if [[ ${NUM_FAILED} == 0 ]]; then
          BADGE_COLOR=brightgreen
        else
          BADGE_COLOR=yellow
        fi
        BADGE_MESSAGE="${NUM_PASSED}/${NUM_TESTS} passed"
        SUMMARY="${{ inputs.NAME }} on ${{ inputs.GPU_ARCH }}: ${NUM_TESTS} total tests, ${NUM_ERRORS} errors, ${NUM_PASSED} passed, ${NUM_FAILED} failed."
      fi

      source .github/workflows/scripts/to_json.sh
      BADGE_LABEL="${{ inputs.NAME }} ${{ inputs.GPU_ARCH }} Unit"
      to_json \
        SUMMARY \
        NUM_ERRORS NUM_TESTS NUM_PASSED NUM_FAILED \
        BADGE_LABEL BADGE_COLOR BADGE_MESSAGE \
      > sitrep.json
      
      schemaVersion=1 \
      label="${BADGE_LABEL}" \
      message="${BADGE_MESSAGE}" \
      color="${BADGE_COLOR}" \
      to_json schemaVersion label message color \
      > badge-${{ inputs.NAME }}-${{ inputs.GPU_ARCH }}.json

  - name: Upload statistics artifacts
    if: ${{ !cancelled() }}
    uses: actions/upload-artifact@v6
    with:
      name: ${{ inputs.NAME }}-${{ inputs.GPU_ARCH }}
      path: |
        sitrep.json
        badge-${{ inputs.NAME }}-${{ inputs.GPU_ARCH }}.json

  - name: Clean up xpk environment from runner
    if: ${{ always() }}
    shell: bash -x -u {0}
    run: |
      sudo rm -rf ${JOBSET_NAME}
