###############################################################################
## T5X
###############################################################################

ARG BASE_IMAGE=ghcr.io/nvidia/jax:latest
FROM ${BASE_IMAGE}
ARG REPO_TE="https://github.com/NVIDIA/TransformerEngine.git"
ARG REF_TE=main
ARG SRC_PATH_TE=/opt/transformer-engine

ADD install-te.sh /usr/local/bin
RUN install-te.sh --from=${REPO_TE} --ref=${REF_TE} --dir=${SRC_PATH_TE}