ARG BASE_IMAGE
FROM ${BASE_IMAGE} as mealkit
FROM mealkit as final
COPY .github/gke-workflow/nccl/scripts /scripts
RUN apt-get update \
    && apt install -y openssh-server
RUN passwd -d root && \
     echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
     echo "PermitEmptyPasswords yes" >> /etc/ssh/sshd_config && \
     echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config && \
     chmod +x /scripts/*

