# syntax=docker/dockerfile:1-labs

ARG BASE_IMAGE=ghcr.io/nvidia/jax-mealkit:jax
ARG URLREF_AF=https://github.com/google-deepmind/alphafold3#main
ARG SRC_PATH_AF=/opt/alphafold

###############################################################################
## Download source and add auxiliary scripts
###############################################################################

FROM ${BASE_IMAGE} AS mealkit
ARG URLREF_AF
ARG SRC_PATH_AF


RUN <<"EOF" bash -ex -o pipefail
git-clone.sh ${URLREF_AF} ${SRC_PATH_AF}
EOF


RUN <<"EOF" bash -ex -o pipefail
sed -i '/"jax==/d' ${SRC_PATH_AF}/pyproject.toml
sed -i '/"jax[cuda12]==/d' ${SRC_PATH_AF}/pyproject.toml
echo "-e file://${SRC_PATH_AF}" >> /opt/pip-tools.d/requirements-af.in
EOF

###############################################################################
## Add test script to the path
###############################################################################

#ADD test-af3.sh /usr/local/bin

###############################################################################
## Install accumulated packages from the base image and the previous åstage
###############################################################################

FROM mealkit AS final

RUN pip-finalize.sh

WORKDIR ${SRC_PATH_AF}
