###############################################################################
## T5X
###############################################################################

ARG BASE_IMAGE=ghcr.io/nvidia/jax:latest
FROM ${BASE_IMAGE}

ADD install-t5x.sh /usr/local/bin
RUN install-t5x.sh

ADD test-t5x.sh /usr/local/bin