jax:
  url: https://github.com/google/jax.git
  tracking_ref: main
  latest_verified_commit: b32e191e22eeb8c2475a8866d91b51e34ab4bfc8
  mode: git-clone
xla:
  url: https://github.com/openxla/xla.git
  tracking_ref: main
  latest_verified_commit: b47487d935f8aa7067cbe12b211e16a8d23e4b0c
  mode: git-clone
flax:
  url: https://github.com/google/flax.git
  mirror_url: https://github.com/nvjax-svc-0/flax.git
  tracking_ref: main
  mode: git-clone
  patches:
    pull/3340/head: file://patches/flax/PR-3340.patch # Add Sharding Annotations to Flax Modules
  latest_verified_commit: 8485ec3c8d183684ddb0fd4edde61c63b40b6713
transformer-engine:
  url: https://github.com/NVIDIA/TransformerEngine.git
  tracking_ref: main
  latest_verified_commit: b629e6e54cb3197927c0799c5aeca7537adebe68
  mode: git-clone
pydantic:
  version: X.Y.Z
  mode: pip-constraint
dllogger:
  url: https://github.com/NVIDIA/dllogger.git
  tracking_ref: master
  latest_verified_commit: 0478734ff7be75adde8d160e04872664d1c62e5f
  mode: pip-vcs
jestimator:
  url: https://github.com/google-research/jestimator.git
  tracking_ref: main
  latest_verified_commit: 326824a477feef6d92e6f44175000907a72899ca
  mode: pip-vcs
optax:
  url: https://github.com/google-deepmind/optax.git
  tracking_ref: main
  latest_verified_commit: d5c22d3e8a9ed21a2757e1a527387f9651a6d639
  mode: pip-vcs
seqio:
  url: https://github.com/google/seqio.git
  tracking_ref: main
  latest_verified_commit: 48180c68c5fc8ddb15bc98467c388a2132e69983
  mode: pip-vcs
maxtext:
  url: https://github.com/google/maxtext.git
  tracking_ref: main
  latest_verified_commit: 154e9b75c89ad5a6e31e763720c5d87ed2b56bb7
  mode: git-clone
mlperf-logging:
  url: https://github.com/mlcommons/logging.git
  tracking_ref: master
  latest_verified_commit: 050e5a60cb02b7bd5487e0b5869355a9047ebe19
  mode: pip-vcs
equinox:
  url: https://github.com/patrick-kidger/equinox.git
  tracking_ref: main
  latest_verified_commit: 4b25c3d6a9477baeb2b85e4d58b6465a4edc9ff8
  mode: git-clone
orbax-checkpoint:
  url: https://github.com/google/orbax.git
  tracking_ref: main
  latest_verified_commit: 186e394cb949b79e9033f2ac07967a2159f475c0
  mode: pip-vcs
pathwaysutils:
  url: https://github.com/google/pathways-utils.git
  tracking_ref: main
  latest_verified_commit: 40a84b4ff551cefd5fb4eb17162c08b6701cc874
  mode: pip-vcs
axlearn:
  url: https://github.com/apple/axlearn.git
  mirror_url: https://github.com/nvjax-svc-0/axlearn.git
  tracking_ref: main
  mode: git-clone
  patches: {}
  latest_verified_commit: c8624c837c55f39d8e8fc4e513d54b7e19d108f6
qwix:
  url: https://github.com/google/qwix.git
  tracking_ref: main
  latest_verified_commit: 6dc08adf5fd7b48ff35b48e033bc049cae6a8ea1
  mode: git-clone
tunix:
  url: https://github.com/google/tunix.git
  tracking_ref: main
  latest_verified_commit: 21f2f1ed875101b522d8c2953aa201092ccc90a8
  mode: git-clone
torchax:
  url: https://github.com/google/torchax.git
  tracking_ref: main
  latest_verified_commit: 663604c8e6bea50536ca52e3e00db3f7ff5f0359
  mode: git-clone
alphafold:
  url: https://github.com/google-deepmind/alphafold3.git
  tracking_ref: main
  latest_verified_commit: 5a3d6b63656038fbb5285d405cd3389b190a5774
  mode: git-clone
