jax:
  url: https://github.com/google/jax.git
  tracking_ref: main
  latest_verified_commit: b1ad9799f4217f9f0ced5ab0705028a41b0eda8c
  mode: git-clone
xla:
  url: https://github.com/openxla/xla.git
  tracking_ref: main
  latest_verified_commit: 93ac6858e2d01f5f41f0e932a5433bdd4b57a5bc
  mode: git-clone
flax:
  url: https://github.com/google/flax.git
  mirror_url: https://github.com/nvjax-svc-0/flax.git
  tracking_ref: main
  mode: git-clone
  patches:
    pull/3340/head: file://patches/flax/PR-3340.patch # Add Sharding Annotations to Flax Modules
  latest_verified_commit: d1f0d69b49a4f208e0a854039d7914c1c7c431e3
transformer-engine:
  url: https://github.com/NVIDIA/TransformerEngine.git
  tracking_ref: main
  latest_verified_commit: 21a066d257afeaf8039325f58df9a62587517976
  mode: git-clone
pydantic:
  version: X.Y.Z
  mode: pip-constraint
dllogger:
  url: https://github.com/NVIDIA/dllogger.git
  tracking_ref: master
  latest_verified_commit: 0478734ff7be75adde8d160e04872664d1c62e5f
  mode: pip-vcs
jestimator:
  url: https://github.com/google-research/jestimator.git
  tracking_ref: main
  latest_verified_commit: 326824a477feef6d92e6f44175000907a72899ca
  mode: pip-vcs
optax:
  url: https://github.com/google-deepmind/optax.git
  tracking_ref: main
  latest_verified_commit: c435df805f2bc411d678373d19822b448d4e967a
  mode: pip-vcs
seqio:
  url: https://github.com/google/seqio.git
  tracking_ref: main
  latest_verified_commit: 00e306ec53ea2d01281e6bc634333072991963c1
  mode: pip-vcs
maxtext:
  url: https://github.com/google/maxtext.git
  tracking_ref: main
  latest_verified_commit: 1db7b218a5392230c45941c17be5da8ee0b59271
  mode: git-clone
mlperf-logging:
  url: https://github.com/mlcommons/logging.git
  tracking_ref: master
  latest_verified_commit: 8a0cc0558ab498b3b003b106d7eae0de19801876
  mode: pip-vcs
equinox:
  url: https://github.com/patrick-kidger/equinox.git
  tracking_ref: main
  latest_verified_commit: 3990f4b5b37c9946fa4a9d44b65bf05e5f5b5640
  mode: git-clone
orbax-checkpoint:
  url: https://github.com/google/orbax.git
  tracking_ref: main
  latest_verified_commit: 4d263d0ea34150c0ed55cf80089a6cef7e2794f2
  mode: pip-vcs
pathwaysutils:
  url: https://github.com/google/pathways-utils.git
  tracking_ref: main
  latest_verified_commit: 2c71770e0d05373608317a8e3fb553e167d22780
  mode: pip-vcs
axlearn:
  url: https://github.com/apple/axlearn.git
  mirror_url: https://github.com/nvjax-svc-0/axlearn.git
  tracking_ref: main
  mode: git-clone
  patches: {}
  latest_verified_commit: 34aed43c1b6e581c4753d06d7cbeedd5010ef26b
qwix:
  url: https://github.com/google/qwix.git
  tracking_ref: main
  latest_verified_commit: 8555358e157c5fe810cdddc00e2bad8416108b80
  mode: git-clone
tunix:
  url: https://github.com/google/tunix.git
  tracking_ref: main
  latest_verified_commit: 205ae3c44856d63cf6898130301ca13c52185d85
  mode: git-clone
torchax:
  url: https://github.com/google/torchax.git
  tracking_ref: main
  latest_verified_commit: ef79eed53f1efef7475f4b0136d5137d59d5aa57
  mode: git-clone
alphafold:
  url: https://github.com/google-deepmind/alphafold3.git
  tracking_ref: main
  latest_verified_commit: a66cc5226d5fbcf7b08af4495af6fd7262178e38
  mode: git-clone
