jax:
  url: https://github.com/google/jax.git
  tracking_ref: main
  latest_verified_commit: 504d3d965b1558f33c6814a52e2c8bd265078d32
  mode: git-clone
xla:
  url: https://github.com/openxla/xla.git
  tracking_ref: main
  latest_verified_commit: 8f278889468a9e7619243a6c65a0a8d2beb414a4
  mode: git-clone
flax:
  url: https://github.com/google/flax.git
  mirror_url: https://github.com/nvjax-svc-0/flax.git
  tracking_ref: main
  mode: git-clone
  patches:
    pull/3340/head: file://patches/flax/PR-3340.patch # Add Sharding Annotations to Flax Modules
  latest_verified_commit: 7075c6e68eba342f53f98f53f187443dd56ea29d
transformer-engine:
  url: https://github.com/NVIDIA/TransformerEngine.git
  tracking_ref: main
  latest_verified_commit: 5d947a03775797875c90ce1c3cf249d0d3dd33cb
  mode: git-clone
pydantic:
  version: X.Y.Z
  mode: pip-constraint
dllogger:
  url: https://github.com/NVIDIA/dllogger.git
  tracking_ref: master
  latest_verified_commit: 0478734ff7be75adde8d160e04872664d1c62e5f
  mode: pip-vcs
jestimator:
  url: https://github.com/google-research/jestimator.git
  tracking_ref: main
  latest_verified_commit: 326824a477feef6d92e6f44175000907a72899ca
  mode: pip-vcs
optax:
  url: https://github.com/google-deepmind/optax.git
  tracking_ref: main
  latest_verified_commit: 71dc2e7ff966f533167c8b111ce3a79f70db3a7c
  mode: pip-vcs
seqio:
  url: https://github.com/google/seqio.git
  tracking_ref: main
  latest_verified_commit: 48180c68c5fc8ddb15bc98467c388a2132e69983
  mode: pip-vcs
maxtext:
  url: https://github.com/google/maxtext.git
  tracking_ref: main
  latest_verified_commit: b117f50cf0489853ea6a9ce81ad2785a0fde3410
  mode: git-clone
mlperf-logging:
  url: https://github.com/mlcommons/logging.git
  tracking_ref: master
  latest_verified_commit: c28b863cc73d405e584b158238f58d6ad92bd257
  mode: pip-vcs
equinox:
  url: https://github.com/patrick-kidger/equinox.git
  tracking_ref: main
  latest_verified_commit: 5972a417589cf92a6265a9f1703af36cde69f245
  mode: git-clone
orbax-checkpoint:
  url: https://github.com/google/orbax.git
  tracking_ref: main
  latest_verified_commit: 7bf1e4b16a48b64cbade779d323e6fce29839b13
  mode: pip-vcs
pathwaysutils:
  url: https://github.com/google/pathways-utils.git
  tracking_ref: main
  latest_verified_commit: d91f57e9cedf539fcb22d4e26f3b323a75950bcd
  mode: pip-vcs
axlearn:
  url: https://github.com/apple/axlearn.git
  mirror_url: https://github.com/nvjax-svc-0/axlearn.git
  tracking_ref: main
  mode: git-clone
  patches: {}
  latest_verified_commit: b4797145d672eec5a5dcc52f1dfada46963de509
qwix:
  url: https://github.com/google/qwix.git
  tracking_ref: main
  latest_verified_commit: b966dc4ddc763c871c5788167510d769234d1f5a
  mode: git-clone
tunix:
  url: https://github.com/google/tunix.git
  tracking_ref: main
  latest_verified_commit: 51d933546bada179eef06e7abf5d3a23d6826bd6
  mode: git-clone
torchax:
  url: https://github.com/google/torchax.git
  tracking_ref: main
  latest_verified_commit: ed7d9a31e6efa976bbb1f3792f1f1f2f37d50f0a
  mode: git-clone
