name: ~build CUDA+Python base container

on:
  workflow_call:
    inputs:
      ARCHITECTURE:
        type: string
        description: 'CPU architecture to build the image for, e.g. amd64, arm64'
        required: true
      BASE_IMAGE:
        type: string
        description: 'Base CUDA image, e.g. nvidia/cuda:X.Y.Z-devel-ubuntu22.04'
        required: false
        default: latest
      JAX_SRC_REF:
        description: 'JAX source url#branch/commit SHA'
        type: string
        required: false
        default: ''
      XLA_SRC_REF:
        description: 'XLA source url#branch/commit SHA'
        type: string
        required: false
        default: ''
      T5X_SRC_REF:
        description: 'T5X source url#branch/commit SHA'
        type: string
        required: false
        default: ''
      PAXML_SRC_REF:
        description: 'PAXML source url#branch/commit SHA'
        type: string
        required: false
        default: ''
      PRAXIS_SRC_REF:
        description: 'PRAXIS source url#branch/commit SHA'
        type: string
        required: false
        default: ''
      BUILD_DATE:
        type: string
        description: "Build date in YYYY-MM-DD format"
        required: false
        default: 'NOT SPECIFIED'
      ARTIFACT_NAME:
        type: string
        description: 'Name of the artifact zip file'
        required: false
        default: 'artifact-base-build'
      BADGE_FILENAME:
        type: string
        description: 'Name of the endpoint JSON file for shields.io badge'
        required: false
        default: 'badge-base-build'
      GIT_USER_NAME:
        type: string
        description: 'Username in GIT to perform git pull/push'
        required: false
        default: 'JAX Toolbox'
      GIT_USER_EMAIL:
        type: string
        description: 'User email in GIT to perform git pull/push'
        required: false
        default: 'jax@nvidia.com'
      BUMP_MANIFEST:
        type: boolean
        description: "Flag to bump manifest file or not"
        default: false
        required: false         
    outputs:
      DOCKER_TAG:
        description: "Tag of the image built"
        value: ${{ jobs.build-base.outputs.DOCKER_TAG }}

env:
  UPLD_IMAGE: ghcr.io/nvidia/jax-toolbox-internal

permissions:
  contents: read  # to fetch code
  actions:  write # to cancel previous workflows
  packages: write # to upload container

jobs:

  bump-manifest:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository under ${GITHUB_WORKSPACE}
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Setup SSH known hosts
        id: ssh-known-hosts
        run: |
          mkdir -p ~/.ssh
          cat >> ~/.ssh/known_hosts << EOF
          ${{ vars.SSH_KNOWN_HOSTS }}
          EOF
          chmod 600 ~/.ssh/known_hosts
          echo "FILE=$(realpath ~/.ssh/known_hosts)" >> $GITHUB_OUTPUT
          
      - name: Update manifest with xla and jax src
        if: inputs.XLA_SRC_REF || inputs.JAX_SRC_REF || inputs.T5X_SRC_REF
        working-directory: .github/container
        run: |
        
          IFS="#";
          read -ra arr <<< "${{ inputs.JAX_SRC_REF }}";
          JAX_SRC="${arr[0]}";
          JAX_REF="${arr[1]}";

          read -ra arr <<< "${{ inputs.XLA_SRC_REF }}";
          XLA_SRC="${arr[0]}";
          XLA_REF="${arr[1]}";

          read -ra arr <<< "${{ inputs.T5X_SRC_REF }}";
          T5X_SRC="${arr[0]}";
          T5X_REF="${arr[1]}";

          read -ra arr <<< "${{ inputs.PAXML_SRC_REF }}";
          PAXML_SRC="${arr[0]}";
          PAXML_REF="${arr[1]}";

          read -ra arr <<< "${{ inputs.PRAXIS_SRC_REF }}";
          PRAXIS_SRC="${arr[0]}";
          PRAXIS_REF="${arr[1]}";


          echo "JAX_SRC: ${JAX_SRC}";
          echo "JAX_REF: ${JAX_REF}";
          echo "XLA_SRC: ${XLA_SRC}";
          echo "XLA_REF: ${XLA_REF}";
          echo "T5X_SRC: ${T5X_SRC}";
          echo "T5X_REF: ${T5X_REF}";
          echo "PAXML_SRC: ${PAXML_SRC}";
          echo "PAXML_REF: ${PAXML_REF}";
          echo "PRAXIS_SRC: ${PRAXIS_SRC}";
          echo "PRAXIS_REF: ${PRAXIS_REF}";

          echo "JAX_SRC_REF: ${{ inputs.JAX_SRC_REF }}";
          echo "XLA_SRC_REF: ${{ inputs.XLA_SRC_REF }}";
          echo "T5X_SRC_REF: ${{ inputs.T5X_SRC_REF }}";
          echo "PAXML_SRC_REF: ${{ inputs.PAXML_SRC_REF }}";
          echo "PRAXIS_SRC_REF: ${{ inputs.PRAXIS_SRC_REF }}";
          
          if [[ -n ${JAX_SRC} ]]; then
            echo "UPDATING JAX_SRC: ${JAX_SRC}";
            yq e ".jax.url = \"$JAX_SRC\"" -i manifest.yaml
          fi
          if [[ -n ${JAX_REF} ]]; then
            echo "UPDATING JAX_REF: ${JAX_REF}";
            export JAX_SHA=$(git ls-remote --heads --refs ${JAX_SRC} "refs/heads/${JAX_REF}" 2>/dev/null | awk '{print $1}')
            yq e '.jax.latest_verified_commit = strenv(JAX_SHA)' -i manifest.yaml
          fi
          if [[ -n ${XLA_SRC} ]]; then
            echo "UPDATING XLA_SRC: "${XLA_SRC}"";
            yq e ".xla.url = \"$XLA_SRC\"" -i manifest.yaml
          fi
          if [[ -n ${XLA_REF} ]]; then
            echo "UPDATING XLA_REF ${XLA_REF}";
            yq e ".xla.latest_verified_commit =\"$XLA_REF\"" -i manifest.yaml
            echo "Updated XLA REF";
            cat manifest.yaml;
          fi
          if [[ -n ${T5X_SRC} ]]; then
            echo "UPDATING T5X_SRC ${T5X_SRC}";
            yq e ".t5x.url = \"$T5X_SRC\"" -i manifest.yaml
          fi
          if [[ -n ${T5X_REF} ]]; then
            echo "UPDATING T5X_REF ${T5X_REF}";
            export T5X_SHA=$(git ls-remote --heads --refs ${T5X_SRC} "refs/heads/${T5X_REF}" 2>/dev/null | awk '{print $1}')
            yq e '.xla.latest_verified_commit = strenv(T5X_SHA)' -i manifest.yaml
          fi
          if [[ -n ${PAXML_SRC} ]]; then
            echo "UPDATING PAXML_SRC ${PAXML_SRC}";
            yq e ".paxml.url = \"$PAXML_SRC\"" -i manifest.yaml
          fi
          if [[ -n ${PAXML_REF} ]]; then
            echo "UPDATING PAXML_REF ${PAXML_REF}";
            export PAXML_SHA=$(git ls-remote --heads --refs ${PAXML_SRC} "refs/heads/${PAXML_REF}" 2>/dev/null | awk '{print $1}')
            yq e '.xla.latest_verified_commit = strenv(PAXML_SHA)' -i manifest.yaml
          fi
          if [[ -n ${PRAXIS_SRC} ]]; then
            echo "UPDATING PRAXIS_SRC ${PRAXIS_SRC}";
            yq e ".praxis.url = \"$PRAXIS_SRC\"" -i manifest.yaml
          fi
          if [[ -n ${PRAXIS_REF} ]]; then
            echo "UPDATING PRAXIS_REF ${PRAXIS_REF}";
            export PRAXIS_SHA=$(git ls-remote --heads --refs ${PRAXIS_SRC} "refs/heads/${PRAXIS_REF}" 2>/dev/null | awk '{print $1}')
            yq e '.xla.latest_verified_commit = strenv(PRAXIS_SHA)' -i manifest.yaml
          fi
          echo "UPDATED MANIFEST IS: ";
          cat manifest.yaml;
          
      - name: Update manifest and patches in-place - show diff
        if: inputs.BUMP_MANIFEST
        working-directory: .github/container
        shell: bash -x -e {0}
        run: |
          bash bump.sh --input-manifest manifest.yaml
          git diff

      - name: Upload bumped manifest to be used in build-base
        uses: actions/upload-artifact@v3
        with:
          name: maybe-bumped-manifest
          path: .github/container/manifest.yaml
      
      - name: Upload patch folder to be used in build-base
        if: inputs.BUMP_MANIFEST
        uses: actions/upload-artifact@v3
        with:
          name: maybe-bumped-patches
          path: .github/container/patches

  build-base:
    needs: bump-manifest
    runs-on: [self-hosted, "${{ inputs.ARCHITECTURE }}", small]
    env:
      BADGE_FILENAME_FULL: ${{ inputs.BADGE_FILENAME }}-${{ inputs.ARCHITECTURE }}.json
    outputs:
      DOCKER_TAG: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Print environment variables
        run: env

      - name: Check out the repository under ${GITHUB_WORKSPACE}
        uses: actions/checkout@v3

      - name: Delete checked-out manifest and patches
        if: inputs.BUMP_MANIFEST
        run: |
          rm .github/container/manifest.yaml
          rm -rf .github/container/patches

      - name: Replace checked-out manifest file with bumped one
        uses: actions/download-artifact@v3
        with:
          name: maybe-bumped-manifest
          path: .github/container/
      
      - name: Replace checked-out patch folder with bumped one
        if: inputs.BUMP_MANIFEST
        uses: actions/download-artifact@v3
        with:
          name: maybe-bumped-patches
          path: .github/container/patches

      - name: Log the changes in manifest file and patch folder
        working-directory: .github/container
        shell: bash -x -e {0}
        run: |
          ls -lah
          ls -lah patches
          echo "Changes in manifest file and patch folder"
          git diff

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:v0.12.1

      - name: Set docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.UPLD_IMAGE }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ github.run_id }}-base-${{ inputs.ARCHITECTURE }}
          labels:
            org.opencontainers.image.created=${{ inputs.BUILD_DATE }}

      - name: Build docker images
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .github/container
          push: true
          file: .github/container/Dockerfile.base
          platforms: linux/${{ inputs.ARCHITECTURE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_USER_NAME=${{ inputs.GIT_USER_NAME }}
            GIT_USER_EMAIL=${{ inputs.GIT_USER_EMAIL }}
            BUILD_DATE=${{ inputs.BUILD_DATE }}
            ${{ inputs.BASE_IMAGE != 'latest' && format('BASE_IMAGE={0}', inputs.BASE_IMAGE) }}
        
      - name: Generate sitrep
        if: success() || failure()
        shell: bash -x -e {0}
        run: |
          # bring in utility functions
          source .github/workflows/scripts/to_json.sh

          badge_label='Base image ${{ inputs.ARCHITECTURE }} build'
          tags="${{ steps.meta.outputs.tags }}"
          digest="${{ steps.build.outputs.digest }}"
          outcome="${{ steps.build.outcome }}"

          if [[ ${outcome} == "success" ]]; then
            badge_message="pass"
            badge_color=brightgreen
            summary="Base image build on ${{ inputs.ARCHITECTURE }}: $badge_message"
          else
            badge_message="fail"
            badge_color=red
            summary="Base image build on ${{ inputs.ARCHITECTURE }}: $badge_message"
          fi

          to_json \
            summary \
            badge_label tags digest outcome \
          > sitrep.json

          schemaVersion=1 \
          label="${badge_label}" \
          message="${badge_message}" \
          color="${badge_color}" \
          to_json schemaVersion label message color \
          > ${{ env.BADGE_FILENAME_FULL }}

      - name: Upload sitrep and badge
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.ARTIFACT_NAME }}-${{ inputs.ARCHITECTURE }}
          path: |
            sitrep.json
            ${{ env.BADGE_FILENAME_FULL }}
