name: "~Sandbox"

on:
  workflow_dispatch:

jobs:
  t5x-multi-gpu:
    strategy:
      matrix:
        include:
          - TEST_NAME: ["1P1G", "1P2G", "1P4G"]
            N_GPU: [1, 2, 4]
            ADDITIONAL_ARGS: ""
          # - TEST_NAME: ["1P8G"]
          #   N_GPU: [8]
          # - TEST_NAME: ["1P1G_fmha", "1P2G_fmha"]
          #   N_GPU: [1,2]
          #   ADDITIONAL_ARGS: "--enable-fmha 1"
      fail-fast: false

    runs-on: ubuntu-22.04

    steps:
      - name: Check concatination
        run: |
          cuda_start_idx=0
          cuda_end_idx=0
          MAX_GPUS_PER_NODE=8
          n_gpus=(${{ join(matrix.N_GPU, ' ') }})
          test_names=(${{ join(matrix.TEST_NAME, ' ') }})
          test_count=$(wc ${{ join(matrix.N_GPU, ' ') }})
          for idx in $(seq 0 $((test_count-1))); do
            if [[ $cuda_start_idx > $MAX_GPUS_PER_NODE ]]; then
                echo "CUDA GPU idx is greater than number of available GPUs"
                exit 1
            fi
            n_gpu=n_gpus[$idx]
            cuda_end_idx=$((cuda_start_idx + n_gpu - 1))
            cuda_visible_devices=$(seq $cuda_start_idx $cuda_end_idx)
            echo ${n_gpu}, $cuda_visible_devices
            cuda_start_idx=$((cuda_end_idx+1))
          done
