name: "~Sandbox"

on:
  workflow_dispatch:

jobs:
  sandbox:
    runs-on: ubuntu-22.04
    steps:
      - name: Build with some params
        uses: docker/build-push-action@v5
        with:
          context: .github/container
          push: true
          file: Dockerfile.base
          platforms: linux/amd64
          target: mealkit
          tags: test
          ssh: default
          secret-files: |
            "SSH_KNOWN_HOSTS=${{ steps.ssh-known-hosts.outputs.FILE }}"
          build-args: |
            GIT_USER_NAME=blah
            