name: ~run NCCL tests

on:
  workflow_call:
    inputs:
      CONTAINER:
        type: string
        description: Container to test; assumed to already contain {all_gather,all_reduce,broadcast,reduce_scatter}_perf_mpi in $PATH
        required: true

permissions:
  actions:  write # to cancel previous workflows
  contents: read  # to fetch code
  packages: write # to upload container

jobs:
  nccl-test-gke:
    uses: ./.github/workflows/_test_nccl_gke.yaml
    with:
      JAX_IMAGE: ${{ inputs.CONTAINER }}
    secrets: inherit

