name: ~Test MaxText (GKE, XPK)

on:
  workflow_call:
    inputs:
      MAXTEXT_IMAGE:
        type: string
        description: MaxText image from ghcr.io/nvidia
        default: ghcr.io/nvidia/jax:maxtext
        required: false

jobs:
  maxtext-gke:
    runs-on: gke-a3mega
    strategy:
      fail-fast: false
      matrix:
        include:
          - test: maxtext-dot-product-gke
            nodes: 2
            gpus: 8
            model: llama2-7b
            pipeline-parallel: 1
            data-parallel: 1
            fsdp: 2
            tensor-parallel: 4
            attention: dot_product
            remat-policy: minimal_with_context
          - test: maxtext-cudnn-flash-te-gke
            nodes: 2
            gpus: 8
            model: llama2-7b
            pipeline-parallel: 1
            data-parallel: 1
            fsdp: 2
            tensor-parallel: 4
            attention: cudnn_flash_te
            remat-policy: minimal_with_context

    steps:
    - uses: actions/checkout@v6

    - name: Run XPK workload on cluster
      uses: ./.github/actions/gke-xpk
      with:
        IMAGE: ${{ inputs.MAXTEXT_IMAGE }}
        NAME: ${{ matrix.test }}
        ENVS: |
            CUDNN_FRONTEND_CUDART_LIB_NAME=libcudart.so.13
        COMMAND: |
          source \${NCCL_LIB_DIR}/nccl-env-profile.sh;
          nsys-jax --capture-range=cudaProfilerApi \
                   --capture-range-end=stop \
                   -o /opt/output/profile.zip \
                   -- \
                   test-maxtext.sh --nodes ${{ matrix.nodes }} \
                                   --batch-per-gpu 2 \
                                   --model-name=${{ matrix.model }} \
                                   --attn-type=${{ matrix.attention }} \
                                   --remat-policy=${{ matrix.remat-policy }} \
                                   --steps=20 \
                                   --pipeline-parallel ${{ matrix.pipeline-parallel }} \
                                   --data-parallel ${{ matrix.data-parallel }} \
                                   --fsdp ${{ matrix.fsdp }} \
                                   --tensor-parallel ${{ matrix.tensor-parallel }} \
                                   --multiprocess \
                                   -a 'scan_layers=false
                                       max_target_length=4096
                                       use_iota_embed=true
                                       logits_dot_in_fp32=false
                                       profiler=nsys
                                       upload_all_profiler_results=true
                                       skip_first_n_steps_for_profiler=10
                                       profiler_steps=10' |&
          tee /opt/output/output.log &> /dev/stdout;
          EXIT_CODE=\${PIPESTATUS[0]};
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NVCR_TOKEN: ${{ secrets.NVCR_TOKEN }}
