name: EKS JobSet

on:
 push:
    branches:
      - aybchan/eks-jobset-test

permissions:
  contents: read        # to fetch code
  actions:  write       # to cancel previous workflows
  packages: write       # to upload containers

jobs:
  test-jax:
    strategy:
      fail-fast: false
      matrix:
        include:
          - test: backend-independent
            gpus: 1
          #- test: single-gpu
          #  gpus: 1
          #- test: multi-gpu
          #  gpus: 8
    runs-on: eks
    steps:
      - uses: actions/checkout@v4
      - name: Run eks-jobset action
        uses: ./.github/actions/eks-jobset
        with:
          NAME: jax-unit-${{ matrix.test }}
          NUM_GPUS: ${{ matrix.gpus }}
          IMAGE: ghcr.io/nvidia/jax-toolbox-internal:24448213493-jax-amd64
          COMMAND: |
            test-jax.sh -b ${{ matrix.test }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NVCR_TOKEN: ${{ secrets.NVCR_TOKEN }}
          STATISTICS: true
  test-te:
    strategy:
      fail-fast: false
      matrix:
        include:
          - test: L0_jax_unittest
            gpus: 8
          - test: L0_jax_distributed_unittest
            gpus: 8
    runs-on: eks
    steps:
      - uses: actions/checkout@v4
      - name: Run eks-jobset action
        uses: ./.github/actions/eks-jobset
        with:
          NAME: te-${{ matrix.test }}
          NUM_GPUS: ${{ matrix.gpus }}
          IMAGE: ghcr.io/nvidia/jax-toolbox-internal:24448213493-jax-amd64
          # Start MPS daemon
          # TE's default is slightly different, without the hyphen
          # 1 GPU per worker, 3 workers per GPU
          ## 8 GPUs per worker, 1 worker per GPU. pytest-xdist.sh allows aggregation
          ## into a single .jsonl file of results from multiple pytest invocations
          ## inside the test.sh script, so it's useful even with a single worker per
          ## device.
          COMMAND: |
            set -xu -o pipefail;

            mkdir -p /opt/output;

            pip install pytest-reportlog pytest-xdist;
            nvidia-cuda-mps-control -d;
            export TE_PATH=\${SRC_PATH_TRANSFORMER_ENGINE};

            [[ "${{ matrix.test }}" == *unittest* ]] && xdist_args=(4 1) || xdist_args=(8 1);
            pytest-xdist.sh \${xdist_args[@]} /opt/output/pytest-report.jsonl bash \${TE_PATH}/qa/${{ matrix.test }}/test.sh
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NVCR_TOKEN: ${{ secrets.NVCR_TOKEN }}
          STATISTICS: true
          STATISTICS_SCRIPT: |
            report_json=\${JOBSET_NAME}/pytest-report.jsonl
            summary_line=$(tail -n1 \${JOBSET_NAME}/*.log);
            NUM_ERRORS=\$(echo \$summary_line | grep -oE '[0-9]+ error' | awk '{print \$1} END { if (!NR) print 0}');
            NUM_PASSED=\$(cat \$report_json | jq -r 'select(.\"\$report_type\" == "TestReport" and .when == "call" and .outcome == "passed") | .outcome' | wc -l);
            NUM_FAILED=\$(cat \$report_json | jq -r 'select(.\"\$report_type\" == "TestReport" and .when == "call" and .outcome == "failed") | .outcome' | wc -l);
            NUM_TESTS=\$((NUM_FAILED + NUM_PASSED));

  test-nsys-jax:
    runs-on: eks
    strategy:
      fail-fast: false
      matrix:
        include:
          - gpus: 8
    steps:
      - uses: actions/checkout@v4
      - name: Run eks-jobset action
        uses: ./.github/actions/eks-jobset
        with:
          NAME: nsys-jax
          NUM_GPUS: ${{ matrix.gpus }}
          IMAGE: ghcr.io/nvidia/jax-toolbox-internal:24448213493-jax-amd64
          # nsys-jax is already installed, this is just adding the test dependencies
          # abuse knowledge that nsys-jax is installed editable, so the tests exist
          COMMAND: |
            pip install pytest-reportlog nsys-jax[test];
            test_path=\$(python -c 'import importlib.resources; print(importlib.resources.files(\"nsys_jax\").joinpath(\"..\", \"tests\").resolve())');
            pytest --basetemp=/opt/output/pytest-tmp --report-log=/opt/output/pytest-report.jsonl \"\${test_path}\"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NVCR_TOKEN: ${{ secrets.NVCR_TOKEN }}
          STATISTICS: true
          STATISTICS_SCRIPT: |
            report_json=\${JOBSET_NAME}/pytest-report.jsonl
            summary_line=\$(tail -n1 \${JOBSET_NAME}/*.log);
            NUM_ERRORS=\$(echo \$summary_line | grep -oE '[0-9]+ error' | awk '{print \$1} END { if (!NR) print 0}');
            NUM_PASSED=\$(cat \${report_json} | jq -r 'select(.\"\$report_type\" == "TestReport" and .when == "call" and .outcome == "passed") | .outcome' | wc -l);
            NUM_FAILED=\$(cat \${report_json} | jq -r 'select(.\"\$report_type\" == "TestReport" and .when == "call" and .outcome == "failed") | .outcome' | wc -l);
            NUM_TESTS=\$(( NUM_PASSED + NUM_FAILED ))
