name: jax-toolbox-triage pure-Python CI

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main

env:
  TRIAGE_PYTHON_FILES: .github/triage

jobs:
  mypy:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repository under ${GITHUB_WORKSPACE}
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github/triage
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          working-directory: .github/triage
      - name: "Run mypy checks"
        working-directory: .github/triage
        run: uv run mypy .
  pytest:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.8", "3.14"]
      fail-fast: false
    steps:
      - name: Check out the repository under ${GITHUB_WORKSPACE}
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github/triage
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          python-version: '${{ matrix.python-version }}'
          working-directory: .github/triage
      - name: "Run tests"
        working-directory: .github/triage
        run: uv run python -m pytest
  ruff:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        tool: ["check", "format"]
      fail-fast: false
    steps:
      - name: Check out the repository under ${GITHUB_WORKSPACE}
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github/triage
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          working-directory: .github/triage
      - name: "Run ruff ${{ matrix.tool }}"
        working-directory: .github/triage
        run: uv run ruff ${{ matrix.tool }}
